### ISSUE TITLE
undefined method 'schedule_time' for nil:NilClass

### ISSUE THREAD

**Issue by dan-fodorean** [elastic/apm-agent-ruby#1173]
## Describe the bug
When exiting the rails server locally I'm getting the following error about 80% of the time

![image](https://user-images.githubusercontent.com/75855242/138005353-6a3ecafa-fbc0-41b8-b2fb-6f80e9c8e98f.png)

Thinking it's probably due to my setup but not sure about it. Also getting the error in our github build.

``` yml
# elastic-apm.yml
secret_token: <%= ENV['ELASTIC_APM_SECRET_TOKEN'] %>
server_url: <%= ENV['ELASTIC_APM_SERVER_URL'] %>
environment: <%= ENV['RAILS_ENV'] %>
```
``` yml
# application.rb
config.elastic_apm.service_name = "APM-Core-#{ENV['RAILS_ENV']}"
```
## Steps to reproduce
1. Add gem 'elastic-apm' to gemfile
2. Add config
3. Start rails server locally in development mode
4. Close rails server

## Expected behavior
No error when closing the rails server locally.

## Environment

- **OS**: 
- **Ruby version**: 2.6
- **Framework and version**: 
- **APM Server version**: 7.14
- **Agent version**: 4.3.0

## Additional context

I have no other options set for the APM agent.
