### ISSUE TITLE
APM agent is exhausting RAM when APM server is unavailable 

### ISSUE THREAD

**Issue by arekk** [elastic/apm-agent-ruby#1282]
## Describe the bug

If APM server is unavailable for application under a medium/heavy traffic system is starting to crash because RAM is exhausting. In effect system is not responsive and oom-killer is starting to kill application processes.

## Steps to reproduce

- have APM Agent enabled in your Rails application 
- have APM Server on separate machine
- pull out a network plug from machine where APM server run
- wait 5-15min, depends on current traffic
- oom-killer is starting to kill ruby processes because of missing memory with message in logs:
```
Jun 22 13:38:14 www-3 kernel: [1809280.413718] Out of memory: Kill process 5095 (ruby) score 264 or sacrifice child
Jun 22 13:38:14 www-3 kernel: [1809280.420186] Killed process 5095 (ruby) total-vm:1227592kB, anon-rss:525984kB, file-rss:0kB, shmem-rss:0kB
Jun 22 13:38:14 www-3 kernel: [1809280.637924] oom_reaper: reaped process 5095 (ruby), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

## Expected behavior

If APM server is unavailable nothing happening, application works as usual, APM server unavailability has no impact on application, memory usage is not increasing.

## Environment

Ubuntu 18.04.6 LTS
ruby 2.6.8p205 (2021-07-07 revision 67951) [x86_64-linux]
Rails 5.2.7.1
apm-server-8.2.0-linux-x86_64
elastic-apm (4.5.0)

## Additional context

APM server is running on remote machine, not locally.

```yaml
enabled: '1'
service_name: '*******'
secret_token: '*******'
server_url: 'https://apm.*******/'
log_level: <%= Logger::ERROR %>
cloud_provider: 'none'
capture_body: 'errors'
global_labels: 'rails=<%= Rails::VERSION::STRING %>,ruby=<%= RUBY_VERSION %>'
filter_exception_types:
  - 'ActionController::InvalidAuthenticityToken'
  - 'ActionController::RoutingError'
  - 'ActionController::UnknownFormat'
ignore_url_patterns: [ '^/heartbeat' ]
```
