### ISSUE TITLE
Pod name is getting reported as host.name rather than pod.name 

### ISSUE THREAD

**Issue by matschaffer** [elastic/apm-agent-ruby#1292]
## Describe the bug

When viewing the Inventory UI with Ruby APM service active in a kubernetes pod, we end up with the ruby service showing up as a "host"

## Steps to reproduce

1. Run a ruby APM instruemented service in a k8s pod
2. Ingest that into ES
3. Open the Infra UI

Can use edge-oblt for the above.

## Expected behavior

Only _hosts_ (VMs) are expected to be present in the infra UI. Since Ruby APM data contains `host.name` we end up showing that as a host as well. Other APM agents don't exhibit the same behavior.

## Additional context

Screenshot from edge-oblt

<img width="947" alt="Screenshot 2022-07-19 at 11 20 49 (1)" src="https://user-images.githubusercontent.com/690/180127465-f9332fc1-79ac-4405-b020-99e050192337.png">

https://github.com/elastic/kibana/issues/133132 was opened for a UI-layer fix, but if other APM agents don't do this, we might be looking at a bug (or at least unexpected behavior) in the Ruby agent.

cc @miltonhultgren @kuisathaverat

**Comment by miltonhultgren** [comment]
I don't know much more than what I wrote in the linked issue and what can be seen on the UI side. 

We have some Ruby service that uses the APM Ruby agent that the Observability Robots team runs inside of Kubernetes, and unlike the other APM agents, the Ruby agent reports the pod name as `host.name` which makes it show up in the Inventory view as a "host".

**Comment by matschaffer** [comment]
Cool. I took a swag at populating the issue template then. @estolfo are you able to help with getting this into an appropriate triage queue?

**Comment by estolfo** [comment]
Thanks for reporting this @matschaffer and @miltonhultgren. We'll take a look and get back to you soon.

@jaggederest can you please take a look at this issue and see what it would take to fix it? Thanks

**Comment by jaggederest** [comment]
So I don't see in the Ruby Agent code anywhere we're setting a host name as `host.name`. We report 
`lib/elastic_apm/metadata/system_info/container_info.rb:58`
```
              {
                namespace: kubernetes_namespace,
                node: { name: kubernetes_node_name },
                pod: {
                  name: kubernetes_pod_name,
                  uid: kubernetes_pod_uid
                }
              }
```

and we report

`lib/elastic_apm/transport/serializers/metadata_serializer:84`
```
          base = {
            configured_hostname: keyword_field(system.configured_hostname),
            architecture: keyword_field(system.architecture),
            platform: keyword_field(system.platform),
            kubernetes: keyword_object(system.kubernetes), # data from above nested here
            container: keyword_object(system.container)
          }
          if system.detected_hostname
            base[:detected_hostname] = keyword_field(system.detected_hostname)
          end
```

But those both look like they're behaving as expected. If we could get a dump of what's being reported and see where it differs, I can make it match whatever schema you prefer, but in the medium term we'll have to support both formats since there will be older agents running around. This should be an easy fix once the decision is made, happy to help, just let me know 👍

**Comment by miltonhultgren** [comment]
> a dump of what's being reported

Do you mean an example document that ends up in Elasticsearch or something else?

**Comment by matschaffer** [comment]
@jaggederest lemme know if I can help with anything else once you have a chance to check out the oblt cluster data!

**Comment by miltonhultgren** [comment]
For visibility, I shared these sample documents with @jaggederest on Slack.

[opbeans-ruby.json.zip](https://github.com/elastic/apm-agent-ruby/files/9179508/opbeans-ruby.json.zip)

**Comment by jaggederest** [comment]
I think this is happening because there's a transformer on the APM server side that takes the pod name and puts it into the host.hostname and host.name fields here:

https://github.com/elastic/apm-server/blob/cf8f0a616f94aadb00595c81ccdc2a61aa8ebd2d/internal/model/modelprocessor/hostname.go#L39-L52

I assume this is correct behavior on that basis. I've compared to the equivalent in the python agent and as far as I can tell it should behave identically there. I think we should bring this up with the apm server folks and see if there's something I'm missing, my ability to dive into Go code is limited 👍

**Comment by matschaffer** [comment]
Interesting! I would have expected to see one of the other opbeans services in the same screenshot if that were the case.

Is there someone from @elastic/apm-server who can lend a hand in tracking this down?

**Comment by simitt** [comment]
The current logic how APM Server sets `host.hostname` and `host.name` is complex, but the same for every apm agent. Details in https://github.com/elastic/apm-server/issues/8118.

**Comment by miltonhultgren** [comment]
Could it be something about the particular host the Ruby service runs on or something in the configuration for the Ruby agent that differs from the other ones? @elastic/observablt-robots can you think of anything that might cause the Ruby service to stand out, maybe some decorator config that is different?

**Comment by kuisathaverat** [comment]
the configuration is the same for all Opbeans, this is the Opbeans ruby deployment on k8s, I do not see any option that can change the way the Agent report the hostname, there is no decorator configuration, nor ingest pipeline configured by us, I've seen this behavior since a long time ago:

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: opbeans-ruby
    service: opbeans
  namespace: default
spec:
  containers:
  - env:
    - name: PORT
      value: "3000"
    - name: PGDATABASE
      value: opbeans-ruby
    - name: DATABASE_URL
      value: postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST)/$(PGDATABASE)
    - name: RAILS_ENV
      value: production
    - name: RAILS_LOG_TO_STDOUT
      value: "1"
    - name: ELASTIC_APM_JS_SERVICE_NAME
      value: opbeans-ruby-client
    - name: ELASTIC_APM_SERVICE_NAME
      value: opbeans-ruby
    - name: ELASTIC_APM_ENVIRONMENT
      value: production
    envFrom:
    - secretRef:
        name: opbeans-configuration
    - secretRef:
        name: opbeans-apm-configuration
    image: docker.elastic.co/observability-ci/opbeans-ruby:daily
    imagePullPolicy: Always
    name: opbeans-ruby
    ports:
    - containerPort: 3000
      name: opbeans-ruby
      protocol: TCP
    volumeMounts:
    - mountPath: /app/config/database.yml
      name: config-db
      subPath: database.yml
  imagePullSecrets:
  - name: docker.elastic.co
  volumes:
  - configMap:
      defaultMode: 420
      name: opbbeans-ruby-config
    name: config-db
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-creds
type: Opaque
stringData:
  user: elastic
  postgresql-password: none
  postgres-password: none
  password: none
  replication-password: none
---
apiVersion: v1
kind: Secret
metadata:
  name: opbeans-apm-configuration
type: Opaque
stringData:
  ELASTIC_APM_SERVER_URL: "https://apm.example.com"
  ELASTIC_APM_JS_SERVER_URL: "https://apm.example.com"
  ELASTIC_APM_JS_BASE_SERVER_URL: "https://apm.example.com"
  ELASTIC_APM_LOG_LEVEL: "debug"
  ELASTIC_APM_PROFILING_INFERRED_SPANS_ENABLED: "true"
  ELASTIC_APM_SERVICE_VERSION: "version"
  ELASTIC_APM_JS_BASE_SERVICE_VERSION: "version"
  ELASTIC_APM_ENABLE_LOG_CORRELATION: "true"
  ELASTIC_APM_VERIFY_SERVER_CERT: "true"
  ELASTIC_APM_TRANSACTION_SAMPLE_RATE: "0.5"
  ELASTIC_APM_SECRET_TOKEN: "SuP3RT0K3N"
---
apiVersion: v1
kind: Secret
metadata:
  name: opbeans-configuration
type: Opaque
stringData:
  OPBEANS_SERVICES: "http://opbeans:3000"
  OPBEANS_DT_PROBABILITY: "0.5"
  ELASTIC_APM_LOG_FILE: "stderr"
  REDIS_URL: "redis://redis-master:6379"
  PGHOST: "db-postgresql"
  PGPORT: "5432"
  PGUSER: "elastic"
  PGPASSWORD: "none"
  EXTRA_OPTS: 'breakdownMetrics: true, environment: "testing"'
```
