### ISSUE TITLE
Unset service_name leads to JSON data validation error

### ISSUE THREAD

**Issue by renshuki** [elastic/apm-agent-ruby#176]
Hi there,

I'm getting a 404 data validation error in the logs (see below) concerning ElasticAPM when I start my rails app and do no specify a service_name in the `elastic_apm.yml` configuration.

## Environement
* Rails 5.2.0
* elastic-apm (1.0.0) gem
* elasticsearch-6.3.2
* kibana-6.3.2
* apm-server-6.3.2

## elastic_apm.yml default configuration
```yaml
# Set service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
# Defaults to the name of your Rails app
service_name: ''

# Use if APM Server requires a token
secret_token: ''

# Set custom APM Server URL (default: http://localhost:8200)
server_url: 'http://localhost:8200'

# Set tracking environment to development
environment: "development"
enabled_environments: ['development','production']
```

### Rails development
> [ElasticAPM] POST returned an unsuccessful status code (400)
[ElasticAPM] apm-server's response: {"error":"data validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/service/name] S[#/properties/service/properties/name/pattern] does not match pattern \"^[a-zA-Z0-9 _-]+$\""}

### APM-server
> 2018-07-29T12:56:59.831+0900    ERROR   [request]       beater/handlers.go:414  error handling request        {"request_id": "9ab42231-901d-4958-87a1-f985fae886ba", "method": "POST", "URL": "http://localhost:8200/v1/transactions", "content_length": 1829, "remote_address": "127.0.0.1", "user-agent": "elastic-apm/ruby 1.0.0", "response_code": 400, "error": "data validation error: Problem validating JSON document against schema: I[#] S[#] doesn't validate with \"transaction#\"\n  I[#/service/name] S[#/properties/service/properties/name/pattern] does not match pattern \"^[a-zA-Z0-9 _-]+$\""}

## Rails app name
```shell
Running via Spring preloader in process 12886
Loading development environment (Rails 5.2.0)
irb(main):001:0> Rails.application.class.parent_name
=> "ElasticApm"
```
Even if my rails app name match the allowed characters pattern, the service name is not set in the `elastic_apm.yml`  which leads to the error above.

### Set the service_name in the config file
```yml
# Set service name - allowed characters: a-z, A-Z, 0-9, -, _ and space
# Defaults to the name of your Rails app
service_name: 'rails-app'

# Use if APM Server requires a token
secret_token: ''

# Set custom APM Server URL (default: http://localhost:8200)
server_url: 'http://localhost:8200'

# Set tracking environment to development
environment: "development"
enabled_environments: ['development','production']
```

### Logs (status: 202 accepted)
> 2018-07-29T13:06:08.119+0900    INFO    [request]       beater/handlers.go:242  handled request       {"request_id": "9af72b58-1ecf-4b27-9bf8-a15ed2989a1c", "method": "POST", "URL": "http://localhost:8200/v1/transactions", "content_length": 1910, "remote_address": "127.0.0.1", "user-agent": "elastic-apm/ruby 1.0.0", "response_code": 202}

By setting the service_name everything just works perfectly fine. I didn't dig to much into the ruby agent code yet but one of my guess is the rails app name is not retrieved correctly.

I hope this can be useful!  😄
