### ISSUE TITLE
FrozenError: can't modify frozen String: ""

### ISSUE THREAD

**Issue by FireFart** [elastic/apm-agent-ruby#665]
Since upgrading the apm gem to 3.3.0 the logs are filled with this message. The APM server is a elastic cloud hosted instance

```text
web_1          | E, [2019-12-29T21:32:57.460146 #76] ERROR -- : [ElasticAPM] Couldn't establish connection to APM Server:
web_1          | "#<FrozenError: can't modify frozen String: \"\">"
```

**Comment by mikker** [comment]
Hi @FireFart (great name 😂)

Could you try running the agent with `log_level: 0` and see if you get more information?

**Comment by mikker** [comment]
And maybe provide your agent configuration if anything is set to non-default settings. Thanks!

**Comment by FireFart** [comment]
Adding `log_level: 0` does not give any more information it seems.

elastic_apm.yml:
```yml
# Set service name - allowed characters: 
# a-z, A-Z, 0-9, -, _ and space
# Defaults to the name of your Rails app
service_name: 'xxxx'

# Use if APM Server requires a token
#
secret_token: <%= ENV['APM_TOKEN'] %>

# Set custom APM Server URL (
# default: http://localhost:8200)
#
server_url: <%= ENV['APM_SERVER_URL'] %>

# alpine does not like the amazon certificate it seems
verify_server_cert: false

log_level: 0
```

Environment:
Ruby: 2.7.0 (alpine docker image)
elastic-apm 3.3.0
