### ISSUE TITLE
elastic-apm messes up ruby log level

### ISSUE THREAD

**Issue by FireFart** [elastic/apm-agent-ruby#808]
## Describe the bug
We noticed this behaviour when upgrading to version `3.7.0` - our ruby log level magically changed to `info` (altough it's set to `warn` in `production.rb`). It looks like this change https://github.com/elastic/apm-agent-ruby/issues/751 messes with the default Rails logger and overwrites the value from `production.rb`. As the default apm log level is `INFO` (https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#config-log-level) this produces a lot of unexpected log output.

Temporarly setting
```yml
log_level: 2
```
in `elastic_apm.yml` resolves this issue but this should be fixed in the gem instead.

## Expected behavior
The log level inside Rails should not be changed by this gem, instead it should respect the log level set in the environment.

## Environment

- **OS**: Linux
- **Ruby version**: 2.7.1
- **Framework and version**: Rails 6.0.3.1
- **APM Server version**: elastic cloud
- **Agent version**: 3.7.0

## Additional context

- Agent config options 
  <details>
    <summary>Click to expand</summary>

    ```yml
    service_name: "XXXX"
    secret_token: <%= ENV['APM_TOKEN'] %>
    server_url: <%= ENV['APM_SERVER_URL'] %>
    verify_server_cert: false
    ```
  </details>
